name: mendax
base: core20
version: '1.0'
summary: A CLI spoofer--like asciinema, but in real-time!
description: |
  With Mendax, you can specify a sequence of CLI inputs and outputs, shown as
  you press ENTER.

grade: stable
confinement: strict

apps:
  mendax:
    command: bin/mendax
    plugs:
      - home
      - removable-media

parts:
  mendax:
    plugin: rust
    source: https://github.com/TheSignPainter98/mendax.git
    build-packages:
      - libncurses5-dev
